# Generated by Django 5.2.12 on 2026-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_livro_editora_alter_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(blank=True, related_name='livros', to='core.autor'),
        ),
    ]
