# Generated by Django 5.2.13 on 2026-04-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_livro_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autor',
            new_name='autores',
        ),
    ]
