# Generated by Django 5.2.13 on 2026-09-22 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_itenscompra_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
